ShopITCourses/Controllers/CkeditorController.cs
using Microsoft.AspNetCore.Mvc;

namespace ShopITCourses.Controllers
{
    public class CkeditorController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;

        public CkeditorController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }

        public string Index()
        {
            return "Hello i`m uploader for CKEditor";
        }

        [HttpPost]
        public JsonResult Upload(IFormFile upload)
        {
            if (upload != null && upload.Length > 0)
            { 
                var filename = upload.FileName;
                var path = Path.Combine(_webHostEnvironment.WebRootPath, "files", filename);
                var str = new FileStream(path, FileMode.Create);
                upload.CopyToAsync(str);
                var url = $"{"/files/"}{filename}";
                return Json(new { uploaded = true, url });
            }
            return Json(new { path = "/files/" });
        }

        [HttpGet]
        public async Task<IActionResult> FileBrowser(IFormFile upload)
        {
            var path = new DirectoryInfo(Path.Combine(_webHostEnvironment.WebRootPath, "files"));
            ViewBag.FilesUploads = path.GetFiles();
            return View("FileBrowser");
        }

        [HttpGet]
        public JsonResult Delete(string name)
        {
            var path = new DirectoryInfo(Path.Combine(_webHostEnvironment.WebRootPath, "files"));
            var file = Path.Combine(path.ToString(), name);
            try
            {
                if (System.IO.File.Exists(file))
                {
                    System.IO.File.Delete(file);
                    return Json(new { success = true, message = "Файл успішно видалено." });
                }
                return Json(new { success = false, message = "Файл не знайдено." });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = $"Сталася помилка: {ex.Message}" });
            }
        }
    }
}

ShopITCourses/Views/Ckeditor/FileBrowser.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using System.IO
@{
    Layout = null;
}

@functions {
    public class ImageValidator
    { 
        public static bool isImageByExtension(string file)
        {
            string? extension = System.IO.Path.GetExtension(file)?.ToLowerInvariant();
            if (extension == null) return false;
            string[] supportEx = { ".jpg",".jpeg",".png",".gif",".bmp",".svg" };
            return Array.Exists(supportEx, ext => ext == extension);
        }
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Файли на сервері</title>
    <style>
        .custom-figure {
            flex: 0 0 auto;
            border: 1px solid black;
            padding-right: 20px;
            margin: 0px; 
            height: 100px; 
            display: flex; 
            flex-direction: column;
            justify-content: flex-start;
            align-items: center;
        }
        .d-flex {
            display: flex;
            flex-wrap: wrap; 
            gap: 10px; 
        }
        .custom-figure img {
            margin-bottom: auto;
        }
    </style>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/ckeditor/ckeditor.js"></script>
    <script>
        $(document).ready(function() {
            var urlParams = new URLSearchParams(window.location.search);
            var ckEditorFuncNum = urlParams.get('CKEditorFuncNum');
            $(function () {
                $('img').dblclick(function () {
                    var fileUrl = '/files/'+$(this).attr('title');
                    window.opener.CKEDITOR.tools.callFunction(ckEditorFuncNum, fileUrl);
                    window.close();
                }).hover(function () {
                    $(this).css('cursor', 'pointer');
            })
         })
        })
    </script>
    <script>
            $(document).ready(function () {
            $(document).on("click", "#delete", function (e) {
                e.preventDefault(); 
                const url = $(this).attr("href");
                const fileName = $(this).closest("figure").find("figcaption").text().trim();
                if (confirm('Ви впевнені, що хочете видалити цей файл?\n'+fileName)) {
                    $.ajax({
                        type: "GET",
                        url: url,
                        success: function (response) {
                            if (response.success) {
                                //alert(response.message); 
                                location.reload(); 
                            } else {
                                alert(response.message); 
                            }
                        },
                        error: function () {
                            alert("Сталася помилка при спробі видалити файл. Спробуйте ще раз.");
                        }
                    });
                }
            });
        });
    </script>
</head>
<body>
    <div id="fileExplorer">
        <h3 align="center">Доступні файли на сервері</h3>
        <h4 align="center">Double click - вставити файл</h4>
        <div class="d-flex justify-content-center">
            @foreach (System.IO.FileInfo item in ViewBag.FilesUploads)
            {
                if (ImageValidator.isImageByExtension(item.Name))
                {
                    <figure class="figure text-center custom-figure">
                       <img src="@Url.Content("~/files/" + item.Name)" title="@item.Name" alt="No image" width="100" class="rounded" />
                       <figcaption class="figure-caption text-center"><b>@item.Name</b></figcaption>
                        <a id="delete" asp-controller="Ckeditor" asp-action="Delete" class="btn btn-sm btn-danger" asp-route-name=@item.Name>Видалити</a>
                    </figure>
                    
                }
                else
                {
                    <figure class="figure text-center custom-figure">
                        <img src="@Url.Content("~/images/fileImage.jpg")" title="@item.Name" alt="No image" width="60" class="rounded" />
                        <figcaption class="figure-caption text-center"><b>@item.Name</b></figcaption>
                        <a id="delete" asp-controller="Ckeditor" asp-action="Delete" class="btn btn-sm btn-danger" asp-route-name=@item.Name>Видалити</a>
                    </figure>
                }
            }
        </div>
    </div>
</body>
</html>