ShopITCourses/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using ShopITCourses.Data;
using ShopITCourses.Models;
using ShopITCourses.Utility;

namespace ShopITCourses.Controllers
{
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CartController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            List<ShopingCart> shopingCarts = ShopingCartSession.GetShopingCartSession(HttpContext);
            List<int> productInCart = shopingCarts.Select(x => x.ProductId).ToList();
            List<Product> prodList = _db.Product.Where(x => productInCart.Contains(x.Id)).ToList();
            return View(prodList);
        }

        public IActionResult Remove(int id)
        {
            List<ShopingCart> shopingCarts = ShopingCartSession.GetShopingCartSession(HttpContext);
            shopingCarts.Remove(shopingCarts.FirstOrDefault(x => x.ProductId == id));
            HttpContext.Session.Set(WC.SessionCart, shopingCarts);
            return RedirectToAction(nameof(Index));
        }
    }
}

ShopITCourses/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopITCourses.Data;
using ShopITCourses.Models;

namespace ShopITCourses.Controllers
{
    [Authorize(Roles = $"{WC.ManagerRole}, {WC.AdminRole}")]//Доступ на основі ролів
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Category
        public async Task<IActionResult> Index()
        {
            return View(await _context.Category.ToListAsync());
        }

        // GET: Category/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Category/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CategoryName,DisplayOrder")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Category/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CategoryName,DisplayOrder")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Category/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Category.FindAsync(id);
            if (category != null)
            {
                _context.Category.Remove(category);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Category.Any(e => e.Id == id);
        }
    }
}

ShopITCourses/Controllers/CkeditorController.cs
using Microsoft.AspNetCore.Mvc;

namespace ShopITCourses.Controllers
{
    public class CkeditorController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;

        public CkeditorController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }

        public string Index()
        {
            return "Hello i`m uploader for CKEditor";
        }

        [HttpPost]
        public JsonResult Upload(IFormFile upload)
        {
            if (upload != null && upload.Length > 0)
            { 
                var filename = upload.FileName;
                var path = Path.Combine(_webHostEnvironment.WebRootPath, "files", filename);
                var str = new FileStream(path, FileMode.Create);
                upload.CopyToAsync(str);
                var url = $"{"/files/"}{filename}";
                return Json(new { uploaded = true, url });
            }
            return Json(new { path = "/files/" });
        }

        [HttpGet]
        public async Task<IActionResult> FileBrowser(IFormFile upload)
        {
            var path = new DirectoryInfo(Path.Combine(_webHostEnvironment.WebRootPath, "files"));
            ViewBag.FilesUploads = path.GetFiles();
            return View("FileBrowser");
        }

        [HttpGet]
        public JsonResult Delete(string name)
        {
            var path = new DirectoryInfo(Path.Combine(_webHostEnvironment.WebRootPath, "files"));
            var file = Path.Combine(path.ToString(), name);
            try
            {
                if (System.IO.File.Exists(file))
                {
                    System.IO.File.Delete(file);
                    return Json(new { success = true, message = "Файл успішно видалено." });
                }
                return Json(new { success = false, message = "Файл не знайдено." });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = $"Сталася помилка: {ex.Message}" });
            }
        }
    }
}

ShopITCourses/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopITCourses.DAL.Repository.IRepository;
using ShopITCourses.Data;
using ShopITCourses.Models;
using static System.Net.Mime.MediaTypeNames;

namespace ShopITCourses.Controllers
{
    [Authorize(Policy = "AdminManager")]//Доступ на основі політики доступу
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IProductRepository _prodRepo;

        public ProductController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment, IProductRepository prodRepo)
        {
            _db = context;
            _webHostEnvironment = webHostEnvironment;
            _prodRepo = prodRepo;
        }

        // GET: Product
        public async Task<IActionResult> Index()
        {
            var products = await _db.Product.Include(p => p.Category).ToListAsync();
            return View(products);
        }

        // GET: Product/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _db.Product
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Product/Create
        public IActionResult Create()
        {
            //ViewData["CategoryId"] = new SelectList(_db.Category, "Id", "CategoryName");
            //ViewData["CategoryId"] = _prodRepo.GetAllDropDownList("Category");
            return View();
        }

        // POST: Product/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Price,Image,CategoryId")] Product product)
        {
            if (HttpContext.Request.Form.Files.Count == 0)
            {
                ModelState.AddModelError("Image", "Оберіть файл з картинкою");
            }
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;

                //var path = _webHostEnvironment.WebRootPath + WC.ImagePath;

                var path = Path.Combine(_webHostEnvironment.WebRootPath,"images","product");

                var fileName = Guid.NewGuid().ToString();
                var extension = Path.GetExtension(files[0].FileName);
                using (var fileStream = new FileStream(Path.Combine(path, fileName + extension), FileMode.Create))
                {
                    await files[0].CopyToAsync(fileStream);
                }
                product.Image = fileName + extension;
                _db.Add(product);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_db.Category, "Id", "CategoryName", product.CategoryId);
            return View(product);
        }

        // GET: Product/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _db.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_db.Category, "Id", "CategoryName", product.CategoryId);
            return View(product);
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Price,Image,CategoryId")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Product oldProduct = await _db.Product.AsNoTracking().FirstOrDefaultAsync(p => p.Id == id);
                    var files = HttpContext.Request.Form.Files;
                    product.Image = oldProduct.Image;
                    if (files.Count > 0)
                    { 
                        string upload = _webHostEnvironment.WebRootPath + WC.ImagePath;
                        if (oldProduct != null && oldProduct.Image != null)
                        { 
                            var oldFile = Path.Combine(upload, oldProduct.Image);
                            if(System.IO.File.Exists(oldFile))
                            {
                                System.IO.File.Delete(oldFile);
                            }
                        }
                        string fileName = Guid.NewGuid().ToString();
                        string extension = Path.GetExtension(files[0].FileName);
                        using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                        {
                            await files[0].CopyToAsync(fileStream);
                        }
                        product.Image = fileName + extension;
                    }
                    _db.Update(product);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_db.Category, "Id", "CategoryName", product.CategoryId);
            return View(product);
        }

        // GET: Product/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _db.Product
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _db.Product.FindAsync(id);
            if (product != null)
            {
                var file = Path.Combine(_webHostEnvironment.WebRootPath + WC.ImagePath , product.Image);
                try
                {
                    System.IO.File.Delete(file);
                }
                catch { }
                _db.Product.Remove(product);
            }

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _db.Product.Any(e => e.Id == id);
        }
    }
}

ShopITCourses/Views/Shared/_CKEditor.cshtml
<script src="~/assets/vendor/ckeditor/ckeditor.js"></script>
<script src="~/js/editor.js"></script>

ShopITCourses/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using ShopITCourses.Utility
@inject IHttpContextAccessor HttpContextAccesor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Кращі IT курси</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShopITCourses.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Кращі IT курси</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Домашня сторінка</a>
                        </li>
                        @if (User.IsInRole(WC.AdminRole) || User.IsInRole(WC.ManagerRole))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Категорії товару</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Товари</a>
                            </li>
                        }
                        @if (User.IsInRole(WC.AdminRole))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ManagerUsers" asp-action="Index">Користувачі</a>
                            </li>
                        }
                        @if (HttpContextAccesor.HttpContext.Session.Get<List<ShopingCart>>(WC.SessionCart) != null)
                        {
                            <a asp-action="Index" asp-controller="Cart" class="nav-link">
                                @{
                                    var count = HttpContextAccesor.HttpContext.Session.Get<List<ShopingCart>>(WC.SessionCart).Count;
                                }
                                <i class="fas fa-cart-shopping"></i> &nbsp; (@count)
                            </a>
                        }
                        else
                        {
                            <a asp-controller="Cart" asp-action="Index" class="nav-link"><i class="fas fa-cart-shopping"></i> &nbsp; (0)</a>
                        }
                        <div class="ms-auto">
                            <partial name="_LoginPartial" />
                        </div>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
     <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Preloader" />
            @RenderBody()
        </main>
    </div> 

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Інтернет магазин IT Step - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script> 
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ShopITCourses/Views/Shared/_Preloader.cshtml
@{
    Layout = null;
}

<div class="preloader" >
    <svg class="preloader__image" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
        <path fill="currentColor"
              d="M304 48c0 26.51-21.49 48-48 48s-48-21.49-48-48 21.49-48 48-48 48 21.49 48 48zm-48 368c-26.51 0-48 21.49-48 48s21.49 48 48 48 48-21.49 48-48-21.49-48-48-48zm208-208c-26.51 0-48 21.49-48 48s21.49 48 48 48 48-21.49 48-48-21.49-48-48-48zM96 256c0-26.51-21.49-48-48-48S0 229.49 0 256s21.49 48 48 48 48-21.49 48-48zm12.922 99.078c-26.51 0-48 21.49-48 48s21.49 48 48 48 48-21.49 48-48c0-26.509-21.491-48-48-48zm294.156 0c-26.51 0-48 21.49-48 48s21.49 48 48 48 48-21.49 48-48c0-26.509-21.49-48-48-48zM108.922 60.922c-26.51 0-48 21.49-48 48s21.49 48 48 48 48-21.49 48-48-21.491-48-48-48z">
        </path>
    </svg>
</div>

ShopITCourses/Views/Shared/_ProductPartial.cshtml
@using ShopITCourses.Models.ViewModel
@model Product

@{
    List<DetailsVM> detailsVM = new List<DetailsVM>();
    detailsVM = ViewData["DetailsVM"] as List<DetailsVM>;
}

<div class="col-lg-4 col-md-6 pb-4 filter @Model.Category.CategoryName.Replace(' ','_')">
    <div class="card bg-white rounded shadow-sm h-100 d-flex flex-column" style="border:1px solid #222">
        <div class="card-body px-3 pt-3 pb-1">
            <!-- Назва товару -->
            <div class="text-center">
                <label class="font-weight-bold">@Model.Name</label>
            </div>
            <!-- Категорія товару -->
            <div class="text-center my-2">
                <span class="badge p-2 border" style="color:black; background-color:lavenderblush">@Model.Category.CategoryName</span>
            </div>
            <!-- Ціна -->
            <div class="text-center">
                <label><span class="text-info h5">@Model.Price</span> / @WC.Currency</label>
            </div>
        </div>
        <!-- Зображення товару -->
        <div class="text-center">
            <img class="img-fluid d-block mx-auto product-image" width="150" src="@WC.ImagePath@Model.Image" alt="Card image cap">
        </div>
        <!-- Опис товару -->
        <div class="card-body p-1 px-3 row flex-grow-1">
            <div class="col-12 pt-2" style="font-size:13px; text-align:justify">
                <p>@Html.Raw(Model.Description)</p>
            </div>
        </div>
        <!-- Кнопка -->
        <div class="card-footer mt-auto">
            @foreach (var detailVM in detailsVM)
            {
                if (detailVM.ExistsInCart && detailVM.Product.Name == @Model.Name)
                {
                    <a class="btn btn-warning form-control btn-sm p-2" style="height:40px" asp-area="Home" asp-action="Details" asp-route-id="@Model.Id">Товар в кошику</a>
                }
                if (!detailVM.ExistsInCart && detailVM.Product.Name == @Model.Name)
                {
                    <a class="btn btn-success form-control btn-sm p-2" style="height:40px" asp-area="Home" asp-action="Details" asp-route-id="@Model.Id">Детально</a>
                }
            }
        </div>
    </div>
</div>